name: code coverage

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/CodeCoverage.yml'
      - 'source/DefaultEcs.Analyzer/**'
      - 'source/DefaultEcs.Analyzer.Test/**'

jobs:
  code_coverage:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
        
    - name: Collect coverage
      run: dotnet test source\DefaultEcs.Analyzer.Test\DefaultEcs.Analyzer.Test.csproj -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:CoverletOutput=..\..\build\lcov.info /p:TEST=true
      
    - name: Upload to coverall
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: 'build\lcov.info'
